### ISSUE TITLE
Compiling on M1 Mac

### ISSUE THREAD

**Issue by rkimoakbioinformatics** [seq-lang/seq#237]
Hi, I'm trying to run seq on M1 MacBook Air. I have tried the following.

1. `./scripts/deps.sh 2` on the native terminal.

This gave an error "No rule to make target `none.o', needed by `libasmrun.a'.  Stop.", which seems to be related to OCaml (https://github.com/rescript-lang/rescript-compiler/issues/4997).

2. /bin/bash -c "$(curl -fsSL https://seq-lang.org/install.sh)" on the Rosetta-based terminal.

```
test.seq:
print('hello world')
```

`seqc run test.seq` ran fine.
`seqc build test.seq` gave an error:
```
ld: library not found for -lseqrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: process for 'clang' exited with status 1
```

I'd appreciate any help.

**Comment by markhend** [comment]
Hi @rkimoakbioinformatics. Thanks for giving it a try. If you are just wanting to install and run, `/bin/bash -c "$(curl -fsSL https://seq-lang.org/install.sh)"` should get you up and running. `deps.sh` is to install the dependencies if you would like to go down the route of [building from source](https://docs.seq-lang.org/build.html?highlight=deps%20sh#building-from-source).

Since `seqc run` is working, you got most of the way there. Currently, there are some issues with `seqc build` related to static linking that are being fixed for the upcoming release. I see similar issues on Linux.

**Comment by arshajii** [comment]
This particular issue should be resolvable if you just set `DYLD_LIBRARY_PATH`:

```bash
export LD_LIBRARY_PATH=/Users/<username>/.seq/lib/seq
```

Let me know if this works!

**Comment by rkimoakbioinformatics** [comment]
@arshajii That worked on the rosetta terminal (M1 MacBook). Thanks. Hope M1 Mac will be able to run seq natively in the future!

**Comment by rkimoakbioinformatics** [comment]
@markhend Oh and thanks for your reply.
